# Generated by Django 4.1.6 on 2023-02-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='repuestos')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=400)),
                ('precio', models.FloatField()),
                ('stock', models.SmallIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maquinas')),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
                ('stock', models.SmallIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='repuestos')),
            ],
        ),
    ]
