# Generated by Django 4.1.6 on 2023-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSTF', '0002_alter_manuales_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='foto',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/maquinas/generic_equipo.png', upload_to='maquinas'),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='foto',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/repuestos/generic_repuesto.jfif', upload_to='repuestos'),
        ),
    ]
