# Generated by Django 4.1.6 on 2023-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSTF', '0003_alter_maquinas_foto_alter_repuestos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='foto',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/maquinas/generic_equipo.png', null=True, upload_to='maquinas'),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='foto',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/repuestos/generic_repuesto.jfif', null=True, upload_to='repuestos'),
        ),
    ]
