# Generated by Django 4.1.6 on 2023-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSTF', '0004_alter_maquinas_foto_alter_repuestos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuales',
            name='archivo',
            field=models.FileField(upload_to='manuales'),
        ),
    ]
